# Generated by Django 6.0.2 on 2026-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('experience', models.TextField()),
                ('reason_to_join', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
