# Generated by Django 6.0.2 on 2026-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
