# Generated by Django 6.0.5 on 2026-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobseeker_otp_jobseeker_otp_created_at_recruiter_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter')], max_length=20),
        ),
    ]
